export const siteContent = {
  metadata: {
    title: "Smart Maps",
    description: "Peta laboratorium",
  },
  brand: {
    appName: "Smart Maps Labkesda",
    shortName: "Smart Maps",
    logoUrl:
      "https://drive.google.com/thumbnail?id=1KtUkqQREVr_dQVhjYBdv35HgpUUMrAvS&sz=w200",
    logoAlt: "Logo Smart Maps Labkesda",
    regionLabel: "Jawa Barat · DKI Jakarta · Banten",
    organizationName: "ASLABKESDA DPW Jawa Barat-DKI Jakarta-Banten",
    footerTagline: "Smart Maps • Direktori laboratorium kesehatan daerah",
  },
  publicHome: {
    eyebrow: "Smart Maps Labkesda",
    title: "Peta dan Agenda Laboratorium",
    description: "",
    dashboardAccessNote: "",
    toolbar: {
      dashboardLabel: "Dashboard",
      loginLabel: "Login",
    },
    sections: {
      mapEyebrow: "Peta",
      mapTitle: "Sebaran Laboratorium",
      articlesEyebrow: "Artikel",
      articlesTitle: "Artikel Terbaru",
      articlesActionLabel: "Lihat semua artikel",
    },
    metrics: {
      total: "Total",
      westJava: "Jabar",
      jakarta: "DKI",
      banten: "Banten",
    },
    map: {
      loadingLabel: "Memuat peta...",
      searchPlaceholder: "Cari lab, kabupaten, kota, atau kecamatan",
      resetLabel: "Reset peta",
      pointCountSuffix: "titik",
      activeAgendaSuffix: "agenda aktif",
      resultsLabel: "hasil",
      noResultsLabel: "Tidak ada hasil",
      focusPrefix: "Fokus",
      activeCoverageLabel: "Sebaran Aktif",
      labPointLabel: "titik laboratorium",
      selectedAgendaLabel: "Agenda Dipilih",
      defaultAgendaLocationLabel: "Lokasi Agenda",
      detailDrawerTitle: "Detail Laboratorium",
      legend: {
        labLocation: "Lokasi laboratorium",
        activeAgenda: "Agenda aktif",
        searchResults: "Hasil pencarian",
        agendaLocation: "Lokasi agenda",
      },
      labDetail: {
        profileEyebrow: "Informasi Ringkas",
        contactSectionTitle: "Kontak & Akses",
        phoneLabel: "Telepon",
        websiteLabel: "Website",
        coordinatesLabel: "Koordinat",
        locationAccessLabel: "Akses Lokasi",
        openMapsLabel: "Buka di Google Maps",
        photoSectionTitle: "Foto Laboratorium",
        structureSectionTitle: "Struktur Utama",
        headRoleLabel: "Kepala Laboratorium",
        adminRoleLabel: "KaSubBag Tata Usaha",
        emptyValueLabel: "Belum diisi",
        unavailableValueLabel: "Belum tersedia",
      },
    },
    sidebar: {
      calendarTitle: "Kalender",
      agendaTitle: "Agenda",
      emptyAgendaLabel: "Belum ada agenda.",
    },
    calendar: {
      weekdayLabels: ["Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min"],
      todayLabel: "Hari Ini",
      detailPrefix: "Detail",
      closeLabel: "Tutup",
      emptyDayLabel: "Belum ada item.",
      readArticleLabel: "Baca artikel",
      viewMapLabel: "Lihat di peta",
      kinds: {
        lab_event: "Agenda Lab",
        article: "Artikel",
        libur_nasional: "Libur Nasional",
        cuti_bersama: "Cuti Bersama",
      },
      scopes: {
        globalArticle: "Artikel Global DPW",
        globalAgenda: "Agenda Global DPW",
      },
    },
    articles: {
      fallbackCoverLabel: "Artikel",
      emptyLabel: "Belum ada artikel.",
      globalOriginLabel: "Global DPW",
      labOriginFallbackLabel: "Artikel Lab",
    },
  },
  login: {
    badge: "Smart Maps Labkesda",
    title: "Login Dashboard Labkesda",
    description: "",
    highlights: [
      "Dashboard berbasis peta",
      "Akses melalui undangan",
      "Aktivasi akun terverifikasi",
    ],
    inviteAlertTitle: "Akses akun tidak bisa daftar langsung",
    inviteAlertDescription:
      "Setiap akun Labkesda harus diundang lebih dulu melalui email. Link undangan akan dipakai untuk membuat password pertama kali.",
    helpText:
      "Jika Anda belum menerima undangan, hubungi super admin untuk mendapatkan akses.",
    signInTitle: "Masuk ke akun Anda",
    signInDescription: "",
    backToMapLabel: "Kembali ke peta",
  },
  admin: {
    modalSubtitle: "Smart Maps Labkesda",
  },
} as const;

export type SiteContent = typeof siteContent;
